#define DHT11_PIN 2
#define DS18B20_PIN 3
#define FLAME_SENSOR_PIN 4
#define MQ2_PIN A0
#define MQ135_PIN A1

#define BUZZER_PIN 5
#define GREEN_LED_PIN 6
#define RED_LED_PIN 7

#define LCD_RS_PIN 8
#define LCD_E_PIN 9
#define LCD_D4_PIN 10
#define LCD_D5_PIN 11
#define LCD_D6_PIN 12
#define LCD_D7_PIN 13

#define ROOM1_TEMP_THRESHOLD 30
#define ROOM2_TEMP_THRESHOLD 30
#define ROOM3_TEMP_THRESHOLD 30

#define GAS_THRESHOLD 300
#define FLAME_DETECTED 1
#define FLAME_NOT_DETECTED 0